REATE DATABASE Colecaolivros;

USE Colecaolivros;

CREATE TABLE usuario (
    USU_ID INT IDENTITY(1,1) PRIMARY KEY,
    USU_NOME VARCHAR(100),
    USU_LOGIN VARCHAR(50),
    USU_SENHA VARCHAR(255),
    USU_TIPO VARCHAR(20) -- Ex: 'usuario', 'admin'
);

CREATE TABLE livro (
    LIV_ID INT IDENTITY(1,1) PRIMARY KEY,
    LIV_NOME VARCHAR(100)
);

CREATE TABLE colecao (
    COL_ID INT IDENTITY(1,1) PRIMARY KEY,
    COL_USU_ID INT,
    COL_LIV_ID INT,
    COL_QTD INT,
    COL_VALOR_UNIT DECIMAL(10,2),
    FOREIGN KEY (COL_USU_ID) REFERENCES usuario(USU_ID),
    FOREIGN KEY (COL_LIV_ID) REFERENCES livro(LIV_ID)
);