CREATE DATABASE login;

USE login;

CREATE TABLE usuarios(
	USUARIOS_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USUARIO_LOGIN VARCHAR(100) NOT NULL,
    USUARIO_SENHA VARCHAR(100) NOT NULL
);

INSERT INTO (USUARIO_LOGIN, USUARIO_SENHA)
VALUES
("admin", "1234");