INSERT INTO funcionarios (FUNC_NOME, FUNC_CPF, FUNC_FUNCAO, FUNC_TEL, FUNC_ATIVO)
VALUES
('João da Silva', '12345678901', 'TI', '11987654321', TRUE)

INSERT INTO usuarios (USU_LOGIN, USU_SENHA, USU_FK_FUNC_ID, USU_ATIVO)
VALUES
('admin', 'admin', 1, TRUE)