CREATE DATABASE Barbearia;

USE Barbearia;

CREATE TABLE funcionarios (
    FUNC_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FUNC_NOME VARCHAR(100) NOT NULL,
    FUNC_CPF VARCHAR(100) NOT NULL,
    FUNC_FUNCAO VARCHAR(100) NOT NULL,
    FUNC_TEL VARCHAR(20) NOT NULL,
    FUNC_ATIVO BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE clientes (
    CLI_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CLI_NOME VARCHAR(100) NOT NULL,
    CLI_CPF VARCHAR(100) NOT NULL,
    CLI_TEL VARCHAR(20) NOT NULL,    
    CLI_DATANASCIMENTO DATE NOT NULL,
    CLI_ATIVO BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE usuarios (
    USU_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USU_LOGIN VARCHAR(100) NOT NULL,
    USU_SENHA VARCHAR(50) NOT NULL,
    USU_FK_FUNC_ID INT NOT NULL,
    USU_ATIVO BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE servicos (
    SERV_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    SERV_NOME VARCHAR(100) NOT NULL,
    SERV_PRECO DECIMAL(10, 2) NULL,    
    SERV_TEMPO INT NULL,
    SERV_ATIVO BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE agenda (
    AGEN_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    AGEN_HORARIO DATETIME NOT NULL,
    AGEN_STATUS CHAR(1),
    AGEN_FK_CLI_ID INT NOT NULL,
    AGEN_FK_FUNC_ID INT NOT NULL,
    AGEN_FK_SERV_ID INT NOT NULL
);

CREATE TABLE venda (
    VEN_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    VEN_DATAHORA DATETIME NOT NULL,
    VEN_TOTAL DECIMAL(10, 2) NOT NULL,
    VEN_FK_AGEN_ID INT NOT NULL
);

ALTER TABLE usuarios ADD CONSTRAINT USU_FUNC FOREIGN KEY (USU_FK_FUNC_ID) REFERENCES funcionarios(FUNC_ID);
ALTER TABLE agenda ADD CONSTRAINT AGEN_CLI FOREIGN KEY (AGEN_FK_CLI_ID) REFERENCES clientes(CLI_ID);
ALTER TABLE agenda ADD CONSTRAINT AGEN_FUNC FOREIGN KEY (AGEN_FK_FUNC_ID) REFERENCES funcionarios(FUNC_ID);
ALTER TABLE agenda ADD CONSTRAINT AGEN_SERV FOREIGN KEY (AGEN_FK_SERV_ID) REFERENCES servicos(SERV_ID);    
ALTER TABLE venda ADD CONSTRAINT VEN_AGEN FOREIGN KEY (VEN_FK_AGEN_ID) REFERENCES agenda(AGEN_ID);

